# Generated by Django 3.2 on 2022-04-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pices',
            new_name='piece',
        ),
    ]
